en: # English
  Language: Language
  Video Segmentation: Video Segmentation
  Layer Divider: Layer Divider
  Upload Input Video: Upload Input Video
  Prompt image with Box & Point: Prompt image with Box & Point
  Preview: Preview
  Model: Model
  Filter Modes: Filter Modes
  Solid Color: Solid Color
  Pixelize: Pixelize
  Pixel Size: Pixel Size
  invert mask: invert mask
  GENERATE PREVIEW: GENERATE PREVIEW
  GENERATE VIDEO: GENERATE VIDEO
  Output Video: Output Video
  Downloadable Output File: Downloadable Output File
  ğŸ“ Open Output folder: ğŸ“ Open Output folder
  Frame Index: Frame Index
  Automatic Segmentation: Automatic Segmentation
  Image Input Mode: Image Input Mode
  Box Prompt: Box Prompt
  Mast Parameters: Mask Parameters
  multimask_output: multimask_output
  Output images will be shown here: Output images will be shown here
  Generated psd file: Generated psd file
  ğŸ“ Open PSD folder: ğŸ“ Open PSD folder
  Video File Format: Video File Format
  Transparent Color (Background Remover): Transparent Color (Background Remover)
  Extracting frames...: Extracting frames...
  GENERATE PSD: GENERATE PSD
  There's no prompt data: There's no prompt data. If you just changed the frame, please remove the drawn points manually with the eraser button and redraw. Sorry, this is a known bug.
  If you don't know how to prompt: If you don't know how to prompt, see [PROMPT_GUIDE.md](https://github.com/jhj0517/sam2-playground/blob/master/docs/PROMPT_GUIDE.md).

ko: # Korean
  Language: ì–¸ì–´
  Video Segmentation: ì˜ìƒ ë¶„í• 
  Layer Divider: ë ˆì´ì–´ ë¶„ë¦¬ê¸°
  Upload Input Video: ì˜ìƒì„ ì—…ë¡œë“œ í•˜ì„¸ìš”
  Prompt image with Box & Point: í”„ë¡¬í”„íŠ¸ (ë°•ìŠ¤ & í¬ì¸íŠ¸)
  Preview: í”„ë¦¬ë·°
  Model: ëª¨ë¸
  Filter Modes: í•„í„° ëª¨ë“œ
  Solid Color: ë‹¨ìƒ‰ (ë°°ê²½ ì œê±°ìš©)
  Pixelize: ëª¨ìì´í¬
  Pixel Size: ëª¨ìì´í¬ í”½ì…€ í¬ê¸°
  invert mask: ë¶„í•  ì˜ì—­ ë°˜ì „
  GENERATE PREVIEW: í”„ë¦¬ë·° ìƒì„±
  GENERATE VIDEO: ì˜ìƒ ìƒì„±
  Output Video: ì˜ìƒ ê²°ê³¼ë¬¼
  Downloadable Output File: ì˜ìƒ íŒŒì¼
  ğŸ“ Open Output folder: ğŸ“ ì¶œë ¥ í´ë” ì—´ê¸°
  Frame Index: ë™ì˜ìƒ í”„ë ˆì„ ìˆ˜
  Automatic Segmentation: ìë™ ë¶„í• 
  Image Input Mode: í”„ë¡¬í”„íŠ¸ ëª¨ë“œ
  Box Prompt: ë°•ìŠ¤ í”„ë¡¬í”„íŠ¸
  Mast Parameters: ë§ˆìŠ¤í¬ íŒŒë¼ë¯¸í„°
  multimask_output: multimask_output
  Output images will be shown here: ë¶„í• ëœ ì´ë¯¸ì§€ë“¤
  Generated psd file: ìƒì„±ëœ psd íŒŒì¼
  ğŸ“ Open PSD folder: ğŸ“ PSD ì¶œë ¥ í´ë” ì—´ê¸°
  Video File Format: ì˜ìƒ íŒŒì¼ í˜•ì‹
  Transparent Color (Background Remover): íˆ¬ëª…ìƒ‰ (ë°°ê²½ ì œê±°ìš©)
  Extracting frames...: ì˜ìƒ í”„ë ˆì„ ì¶”ì¶œ ì¤‘..
  GENERATE PSD: PSD íŒŒì¼ ìƒì„±
  There's no prompt data: í”„ë¡¬í”„íŠ¸ ë°ì´í„°ê°€ ì—†ìŠµë‹ˆë‹¤. ë°©ê¸ˆ ë§‰ í”„ë ˆì„ì„ ë°”ê¾¸ì…¨ë‹¤ë©´, ì§€ìš°ê°œ ë²„íŠ¼ìœ¼ë¡œ í”„ë¡¬í”„íŠ¸ë¥¼ ìˆ˜ë™ìœ¼ë¡œ ì§€ìš°ì‹  í›„ ë‹¤ì‹œ ê·¸ë ¤ì£¼ì„¸ìš”. ì£„ì†¡í•©ë‹ˆë‹¤, ì•„ì§ ê³ ì¹˜ì§€ ëª»í•œ ë²„ê·¸ì…ë‹ˆë‹¤.
  If you don't know how to prompt: í”„ë¡¬í”„íŠ¸ë¥¼ ì–´ë–»ê²Œ ë„£ëŠ”ì§€ ëª¨ë¥´ì‹ ë‹¤ë©´, [PROMPT_GUIDE.md](https://github.com/jhj0517/sam2-playground/blob/master/docs/PROMPT_GUIDE.md)ë¥¼ ë´ì£¼ì„¸ìš”.

ja: # Japanese
  Language: è¨€èª
  Video Segmentation: Video Segmentation
  Layer Divider: Layer Divider
  Upload Input Video: Upload Input Video
  Prompt image with Box & Point: Prompt image with Box & Point
  Preview: Preview
  Model: Model
  Filter Modes: Filter Modes
  Solid Color: Solid Color
  Pixelize: Pixelize
  Pixel Size: Pixel Size
  invert mask: invert mask
  GENERATE PREVIEW: GENERATE PREVIEW
  GENERATE VIDEO: GENERATE VIDEO
  Output Video: Output Video
  Downloadable Output File: Downloadable Output File
  ğŸ“ Open Output folder: ğŸ“ Open Output folder
  Frame Index: Frame Index
  Automatic Segmentation: Automatic Segmentation
  Image Input Mode: Image Input Mode
  Box Prompt: Box Prompt
  Mast Parameters: Mask Parameters
  multimask_output: multimask_output
  Output images will be shown here: Output images will be shown here
  Generated psd file: Generated psd file
  ğŸ“ Open PSD folder: ğŸ“ Open PSD folder
  Video File Format: Video File Format
  Transparent Color (Background Remover): Transparent Color (Background Remover)
  Extracting frames...: Extracting frames...
  GENERATE PSD: GENERATE PSD
  There's no prompt data: There's no prompt data. If you just changed the frame, please remove the drawn points manually with the eraser button and redraw. Sorry, this is a known bug.
  If you don't know how to prompt: If you don't know how to prompt, see [PROMPT_GUIDE.md](https://github.com/jhj0517/sam2-playground/blob/master/docs/PROMPT_GUIDE.md).

es: # Spanish
  Language: Idioma
  Video Segmentation: Video Segmentation
  Layer Divider: Layer Divider
  Upload Input Video: Upload Input Video
  Prompt image with Box & Point: Prompt image with Box & Point
  Preview: Preview
  Model: Model
  Filter Modes: Filter Modes
  Solid Color: Solid Color
  Pixelize: Pixelize
  Pixel Size: Pixel Size
  invert mask: invert mask
  GENERATE PREVIEW: GENERATE PREVIEW
  GENERATE VIDEO: GENERATE VIDEO
  Output Video: Output Video
  Downloadable Output File: Downloadable Output File
  ğŸ“ Open Output folder: ğŸ“ Open Output folder
  Frame Index: Frame Index
  Automatic Segmentation: Automatic Segmentation
  Image Input Mode: Image Input Mode
  Box Prompt: Box Prompt
  Mast Parameters: Mask Parameters
  multimask_output: multimask_output
  Output images will be shown here: Output images will be shown here
  Generated psd file: Generated psd file
  ğŸ“ Open PSD folder: ğŸ“ Open PSD folder
  Video File Format: Video File Format
  Transparent Color (Background Remover): Transparent Color (Background Remover)
  Extracting frames...: Extracting frames...
  GENERATE PSD: GENERATE PSD
  There's no prompt data: There's no prompt data. If you just changed the frame, please remove the drawn points manually with the eraser button and redraw. Sorry, this is a known bug.
  If you don't know how to prompt: If you don't know how to prompt, see [PROMPT_GUIDE.md](https://github.com/jhj0517/sam2-playground/blob/master/docs/PROMPT_GUIDE.md).

fr: # French
  Language: Langue
  Video Segmentation: Video Segmentation
  Layer Divider: Layer Divider
  Upload Input Video: Upload Input Video
  Prompt image with Box & Point: Prompt image with Box & Point
  Preview: Preview
  Model: Model
  Filter Modes: Filter Modes
  Solid Color: Solid Color
  Pixelize: Pixelize
  Pixel Size: Pixel Size
  invert mask: invert mask
  GENERATE PREVIEW: GENERATE PREVIEW
  GENERATE VIDEO: GENERATE VIDEO
  Output Video: Output Video
  Downloadable Output File: Downloadable Output File
  ğŸ“ Open Output folder: ğŸ“ Open Output folder
  Frame Index: Frame Index
  Automatic Segmentation: Automatic Segmentation
  Image Input Mode: Image Input Mode
  Box Prompt: Box Prompt
  Mast Parameters: Mask Parameters
  multimask_output: multimask_output
  Output images will be shown here: Output images will be shown here
  Generated psd file: Generated psd file
  ğŸ“ Open PSD folder: ğŸ“ Open PSD folder
  Video File Format: Video File Format
  Transparent Color (Background Remover): Transparent Color (Background Remover)
  Extracting frames...: Extracting frames...
  GENERATE PSD: GENERATE PSD
  There's no prompt data: There's no prompt data. If you just changed the frame, please remove the drawn points manually with the eraser button and redraw. Sorry, this is a known bug.
  If you don't know how to prompt: If you don't know how to prompt, see [PROMPT_GUIDE.md](https://github.com/jhj0517/sam2-playground/blob/master/docs/PROMPT_GUIDE.md).

de: # German
  Language: Sprache
  Video Segmentation: Video Segmentation
  Layer Divider: Layer Divider
  Upload Input Video: Upload Input Video
  Prompt image with Box & Point: Prompt image with Box & Point
  Preview: Preview
  Model: Model
  Filter Modes: Filter Modes
  Solid Color: Solid Color
  Pixelize: Pixelize
  Pixel Size: Pixel Size
  invert mask: invert mask
  GENERATE PREVIEW: GENERATE PREVIEW
  GENERATE VIDEO: GENERATE VIDEO
  Output Video: Output Video
  Downloadable Output File: Downloadable Output File
  ğŸ“ Open Output folder: ğŸ“ Open Output folder
  Frame Index: Frame Index
  Automatic Segmentation: Automatic Segmentation
  Image Input Mode: Image Input Mode
  Box Prompt: Box Prompt
  Mast Parameters: Mask Parameters
  multimask_output: multimask_output
  Output images will be shown here: Output images will be shown here
  Generated psd file: Generated psd file
  ğŸ“ Open PSD folder: ğŸ“ Open PSD folder
  Video File Format: Video File Format
  Transparent Color (Background Remover): Transparent Color (Background Remover)
  Extracting frames...: Extracting frames...
  GENERATE PSD: GENERATE PSD
  There's no prompt data: There's no prompt data. If you just changed the frame, please remove the drawn points manually with the eraser button and redraw. Sorry, this is a known bug.
  If you don't know how to prompt: If you don't know how to prompt, see [PROMPT_GUIDE.md](https://github.com/jhj0517/sam2-playground/blob/master/docs/PROMPT_GUIDE.md).

zh: # Chinese
  Language: è¯­è¨€
  Video Segmentation: Video Segmentation
  Layer Divider: Layer Divider
  Upload Input Video: Upload Input Video
  Prompt image with Box & Point: Prompt image with Box & Point
  Preview: Preview
  Model: Model
  Filter Modes: Filter Modes
  Solid Color: Solid Color
  Pixelize: Pixelize
  Pixel Size: Pixel Size
  invert mask: invert mask
  GENERATE PREVIEW: GENERATE PREVIEW
  GENERATE VIDEO: GENERATE VIDEO
  Output Video: Output Video
  Downloadable Output File: Downloadable Output File
  ğŸ“ Open Output folder: ğŸ“ Open Output folder
  Frame Index: Frame Index
  Automatic Segmentation: Automatic Segmentation
  Image Input Mode: Image Input Mode
  Box Prompt: Box Prompt
  Mast Parameters: Mask Parameters
  multimask_output: multimask_output
  Output images will be shown here: Output images will be shown here
  Generated psd file: Generated psd file
  ğŸ“ Open PSD folder: ğŸ“ Open PSD folder
  Video File Format: Video File Format
  Transparent Color (Background Remover): Transparent Color (Background Remover)
  Extracting frames...: Extracting frames...
  GENERATE PSD: GENERATE PSD
  There's no prompt data: There's no prompt data. If you just changed the frame, please remove the drawn points manually with the eraser button and redraw. Sorry, this is a known bug.
  If you don't know how to prompt: If you don't know how to prompt, see [PROMPT_GUIDE.md](https://github.com/jhj0517/sam2-playground/blob/master/docs/PROMPT_GUIDE.md).