en:
  Language: Language
  Video Segmentation: Video Segmentation
  Layer Divider: Layer Divider
  Upload Input Video: Upload Input Video
  Prompt image with Box & Point: Prompt image with Box & Point
  Preview: Preview
  Model: Model
  Filter Modes: Filter Modes
  Solid Color: Solid Color
  invert mask: invert mask
  GENERATE PREVIEW: GENERATE PREVIEW
  GENERATE VIDEO: GENERATE VIDEO
  Output Video: Output Video
  Downloadable Output File: Downloadable Output File
  ğŸ“ Open Output folder: ğŸ“ Open Output folder
  Frame Index: Frame Index
  Automatic Segmentation: Automatic Segmentation
  Image Input Mode: Image Input Mode
  Box Prompt: Box Prompt
  Mast Parameters: Mask Parameters
  multimask_output: multimask_output
  Output images will be shown here: Output images will be shown here
  Generated psd file: Generated psd file
  ğŸ“ Open PSD folder: ğŸ“ Open PSD folder

ko:
  Language: ì–¸ì–´
  Video Segmentation: ì˜ìƒ ë¶„í• 
  Layer Divider: ë ˆì´ì–´ ë¶„ë¦¬
  Upload Input Video: ì˜ìƒì„ ì—…ë¡œë“œ í•˜ì„¸ìš”
  Prompt image with Box & Point: ë°•ìŠ¤ & í¬ì¸íŠ¸ í”„ë¡¬í”„íŠ¸
  Preview: í”„ë¦¬ë·°
  Model: ëª¨ë¸
  Filter Modes: í•„í„° ëª¨ë“œ
  Solid Color: ë‹¨ìƒ‰
  invert mask: ë¶„í•  ì˜ì—­ ë°˜ì „
  GENERATE PREVIEW: í”„ë¦¬ë·° ìƒì„±
  GENERATE VIDEO: ì˜ìƒ ìƒì„±
  Output Video: ì˜ìƒ ê²°ê³¼ë¬¼
  Downloadable Output File: ì˜ìƒ íŒŒì¼
  ğŸ“ Open Output folder: ğŸ“ ì¶œë ¥ í´ë” ì—´ê¸°
  Frame Index: ì˜ìƒ í”„ë ˆì„
  Automatic Segmentation: ìë™ ë¶„í• 
  Image Input Mode: í”„ë¡¬í”„íŠ¸ ëª¨ë“œ
  Box Prompt: ë°•ìŠ¤ í”„ë¡¬í”„íŠ¸
  Mast Parameters: ë§ˆìŠ¤í¬ íŒŒë¼ë¯¸í„°
  multimask_output: multimask_output
  Output images will be shown here: ë¶„í• ëœ ì´ë¯¸ì§€ë“¤
  Generated psd file: ìƒì„±ëœ psd íŒŒì¼
  ğŸ“ Open PSD folder: ğŸ“ PSD ì¶œë ¥ í´ë” ì—´ê¸°

ja:
  Language: è¨€èª
  Video Segmentation: Video Segmentation
  Layer Divider: Layer Divider
  Upload Input Video: Upload Input Video
  Prompt image with Box & Point: Prompt image with Box & Point
  Preview: Preview
  Model: Model
  Filter Modes: Filter Modes
  Solid Color: Solid Color
  invert mask: invert mask
  GENERATE PREVIEW: GENERATE PREVIEW
  GENERATE VIDEO: GENERATE VIDEO
  Output Video: Output Video
  Downloadable Output File: Downloadable Output File
  ğŸ“ Open Output folder: ğŸ“ Open Output folder
  Frame Index: Frame Index
  Automatic Segmentation: Automatic Segmentation
  Image Input Mode: Image Input Mode
  Box Prompt: Box Prompt
  Mast Parameters: Mask Parameters
  multimask_output: multimask_output
  Output images will be shown here: Output images will be shown here
  Generated psd file: Generated psd file
  ğŸ“ Open PSD folder: ğŸ“ Open PSD folder

es:
  Language: Idioma
  Video Segmentation: Video Segmentation
  Layer Divider: Layer Divider
  Upload Input Video: Upload Input Video
  Prompt image with Box & Point: Prompt image with Box & Point
  Preview: Preview
  Model: Model
  Filter Modes: Filter Modes
  Solid Color: Solid Color
  invert mask: invert mask
  GENERATE PREVIEW: GENERATE PREVIEW
  GENERATE VIDEO: GENERATE VIDEO
  Output Video: Output Video
  Downloadable Output File: Downloadable Output File
  ğŸ“ Open Output folder: ğŸ“ Open Output folder
  Frame Index: Frame Index
  Automatic Segmentation: Automatic Segmentation
  Image Input Mode: Image Input Mode
  Box Prompt: Box Prompt
  Mast Parameters: Mask Parameters
  multimask_output: multimask_output
  Output images will be shown here: Output images will be shown here
  Generated psd file: Generated psd file
  ğŸ“ Open PSD folder: ğŸ“ Open PSD folder

fr:
  Language: Langue
  Video Segmentation: Video Segmentation
  Layer Divider: Layer Divider
  Upload Input Video: Upload Input Video
  Prompt image with Box & Point: Prompt image with Box & Point
  Preview: Preview
  Model: Model
  Filter Modes: Filter Modes
  Solid Color: Solid Color
  invert mask: invert mask
  GENERATE PREVIEW: GENERATE PREVIEW
  GENERATE VIDEO: GENERATE VIDEO
  Output Video: Output Video
  Downloadable Output File: Downloadable Output File
  ğŸ“ Open Output folder: ğŸ“ Open Output folder
  Frame Index: Frame Index
  Automatic Segmentation: Automatic Segmentation
  Image Input Mode: Image Input Mode
  Box Prompt: Box Prompt
  Mast Parameters: Mask Parameters
  multimask_output: multimask_output
  Output images will be shown here: Output images will be shown here
  Generated psd file: Generated psd file
  ğŸ“ Open PSD folder: ğŸ“ Open PSD folder

de:
  Language: Sprache
  Video Segmentation: Video Segmentation
  Layer Divider: Layer Divider
  Upload Input Video: Upload Input Video
  Prompt image with Box & Point: Prompt image with Box & Point
  Preview: Preview
  Model: Model
  Filter Modes: Filter Modes
  Solid Color: Solid Color
  invert mask: invert mask
  GENERATE PREVIEW: GENERATE PREVIEW
  GENERATE VIDEO: GENERATE VIDEO
  Output Video: Output Video
  Downloadable Output File: Downloadable Output File
  ğŸ“ Open Output folder: ğŸ“ Open Output folder
  Frame Index: Frame Index
  Automatic Segmentation: Automatic Segmentation
  Image Input Mode: Image Input Mode
  Box Prompt: Box Prompt
  Mast Parameters: Mask Parameters
  multimask_output: multimask_output
  Output images will be shown here: Output images will be shown here
  Generated psd file: Generated psd file
  ğŸ“ Open PSD folder: ğŸ“ Open PSD folder


zh:
  Language: è¯­è¨€
  Video Segmentation: Video Segmentation
  Layer Divider: Layer Divider
  Upload Input Video: Upload Input Video
  Prompt image with Box & Point: Prompt image with Box & Point
  Preview: Preview
  Model: Model
  Filter Modes: Filter Modes
  Solid Color: Solid Color
  invert mask: invert mask
  GENERATE PREVIEW: GENERATE PREVIEW
  GENERATE VIDEO: GENERATE VIDEO
  Output Video: Output Video
  Downloadable Output File: Downloadable Output File
  ğŸ“ Open Output folder: ğŸ“ Open Output folder
  Frame Index: Frame Index
  Automatic Segmentation: Automatic Segmentation
  Image Input Mode: Image Input Mode
  Box Prompt: Box Prompt
  Mast Parameters: Mask Parameters
  multimask_output: multimask_output
  Output images will be shown here: Output images will be shown here
  Generated psd file: Generated psd file
  ğŸ“ Open PSD folder: ğŸ“ Open PSD folder